# -*- coding: utf-8 -*-
"""lab2task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VAexYHQzT3Y76aI189r_6oczrYNNQaS
"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print("First 10 numbers:", numbers)

maximum = max(numbers)
minimum = min(numbers)

print("Maximum number:", maximum)
print("Minimum number:", minimum)

numbers.append(20)
numbers.remove(3)
numbers[2] = 3000;
print(numbers);

my_tuple = ("apple", "banana", "cherry", "orange", "grapes")
print("Tuple:", my_tuple)

my_list = list(my_tuple)
print("Converted List:", my_list)

my_list[1] = "grapes"
print(my_list)

"""ist

Mataplotlib

Numpy

tuple
"""

my_tuple = ("apple", "banana", "cherry", "orange", "grapes")
print("Tuple:", my_tuple)
print("First element:", my_tuple[0])
print("Last element:", my_tuple[-1])

temp_list = list(my_tuple)
temp_list[1] = "mango"
my_tuple = tuple(temp_list)
print("Updated Tuple:", my_tuple)

"""set"""

set_a = {1, 2, 3, 4, 5}
set_b = {4, 5, 6, 7, 8}

union_set = set_a | set_b
intersection_set = set_a & set_b
difference_set = set_a - set_b


print("Union:", union_set)
print("Intersection:", intersection_set)
print("Difference (A - B):", difference_set)


set_a.add(10)
set_a.remove(2)

print("Updated set_a:", set_a)

"""Dictionary"""

student = {
    "name": "Hassan",
    "age": 20,
    "course": "Computer Science",
    "roll_no": 101,
    "grade": "A"
}

print("Dictionary:", student)
print("Name:", student["name"])
print("Age:", student["age"])
print("Course:", student["course"])
print("Roll No:", student["roll_no"])
print("Grade:", student["grade"])  # corrected this line

# Example of updating one value
student["age"] = 21
print("Updated Age:", student["age"])